apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: ${{ values.name }}-sockeye-trigger
  labels:
    bridges.triggermesh.io/id: ${{ values.name }}
spec:
  broker: ${{ values.name }}-broker
  filter:
    attributes:
      type: io.triggermesh.${{ values.name }}-function.output
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: ${{ values.name }}-sockeye
