apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  {%- if values.description %}
  description: ${{ values.description }}
  {%- endif %}
  annotations:
    github.com/project-slug: ${{ values.destination.owner + "/" + values.destination.repo }}
    grafana/tag-selector: ${{ values.destination.owner + "/" + values.destination.repo }}
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}
